### ISSUE TITLE
dinger-locations配置中使用*.xml提示找不到文件

### ISSUE THREAD

**Issue by ucfjepl** [AnswerAIL/dingtalk-spring-boot-starter#13]
使用固定文件名称时，exists返回的是true。如果使用*.xml则exists方法返回false
springboot版本是2.3.7
![1](https://user-images.githubusercontent.com/11847554/132672207-c0bd3f42-d6f5-4713-b98a-b8bede4d7fee.png)
![2](https://user-images.githubusercontent.com/11847554/132672212-3ce64efb-722c-4dd3-919c-a544291d9584.png)

**Comment by ucfjepl** [comment]
dinger-spring-boot-starter的版本是1.2.0

**Comment by AnswerAIL** [comment]
@ucfjepl  dinger-locations你是怎么配置的，是下面这样配置的吗

  > dinger-locations: classpath*:config/dinger/*.xml

**Comment by AnswerAIL** [comment]
@ucfjepl 不推荐使用固定文件名称进行配置

**Comment by ucfjepl** [comment]
@AnswerAIL 使用固定文件名称是为了测试
如果使用dinger-locations: classpath*:config/dinger/*.xml配置则提示重复定义的错误
如果使用dinger-locations: classpath:config/dinger/*.xml则提示找不到文件

以下是两种配置的不同异常信息截图
![1](https://user-images.githubusercontent.com/11847554/133013243-44a0f000-e99b-49a9-aa4a-1da5863cbd26.png)
![2](https://user-images.githubusercontent.com/11847554/133013247-2ee17360-3eea-4385-b690-7b802bc171af.png)

**Comment by AnswerAIL** [comment]
@ucfjepl 你是不是用了注解配置又用了xml配置，如果不是的话把你的代码贴出来我看下，提示：报错重复定义是因为你配置了两处一样的消息体

**Comment by AnswerAIL** [comment]
@ucfjepl 好好检查下代码是不是重复配置了消息体，用消息id全局搜一下看，如果采用xml配置消息体用这个配置classpath*:config/dinger/*.xml，当然你也可以用注解方式配置消息体，两种方式任选一种即可

**Comment by ucfjepl** [comment]
@AnswerAIL 找到问题了，应该是两个地方获取资源文件的方式不一致导致的，这样使用junit时就会出现问题。

在使用junit时，DingerAutoConfiguration的checkConfigFileExists方法中使用的resourceLoader.getResource获取不到xml配置，所以提示文件找不到

![1](https://user-images.githubusercontent.com/11847554/133382864-60d19154-b463-4491-8a0d-485dde01167b.png)
![2](https://user-images.githubusercontent.com/11847554/133382870-59ecf462-771e-4e8c-ac75-d1dd84817519.png)

如果在test/resources下面创建一个对应的xml文件，DefaultDingerDefinitionResolver的dingerXmlResolver方法中使用的PathMatchingResourcePatternResolver.getResources会获取到两个配置文件，分别是main/resources和test/resources下的两个文件，此时会提示重复定义的错误

![3](https://user-images.githubusercontent.com/11847554/133383180-82286362-7932-48d4-9f52-2622711ef3f4.png)

是不是应该在DingerAutoConfiguration的checkConfigFileExists和DefaultDingerDefinitionResolver的dingerXmlResolver中使用相同的方式获取资源文件可以解决掉这个问题呢？

**Comment by AnswerAIL** [comment]
@ucfjepl 后面有空了我验证下这个问题，你也可以自己验证下，debug模式下修改resourceLoader引用的对象

**Comment by AnswerAIL** [comment]
@ucfjepl bug已在1.2.1-beta1版本中进行修复，请知悉

**Comment by ucfjepl** [comment]
@AnswerAIL 好的，收到
